[package]
name = "simple_backup"
version = "1.3.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2021"
description = "A minimal application for doing backups."
readme = "README.md"
keywords = ["backup", "compression", "application"]

[dependencies]
tar = "0.4.38"
clap = "2.33"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
yaml-rust = "0.4.5"
chrono = "0.4.19"
regex = "1.5.6"
path-clean = "0.1.0"
path-absolutize = "3.0.13"
indicatif = { version = "0.16.2", features = ["improved_unicode"] }
zstd = { version = "0.11.2", features = ["zstdmt"] }
number_prefix = "0.4.0"
num_cpus = "1.13.1"
iced = { version = "0.4.2", features = ["smol", "pure"], optional = true }
rfd = { version = "0.8.2", optional = true }
dirs = { version = "4.0.0", optional = true }

[dev-dependencies]
tempfile = "3.3.0"

[features]
default = ["gui"]
gui = ["iced", "rfd", "dirs"]
