[package]
name = "simple-backup"
version = "0.4.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2018"
description = "A minimal application for doing backups."
readme = "README.md"
keywords = ["backup", "compression"]

[dependencies]
tar = "0.4"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
yaml-rust = "0.4"
chrono = "0.4"
regex = "1.4"
path-clean = "0.1"
path-absolutize = "3.0"
brotli = { version="3.3", features=["std"] }
indicatif = { version="0.15", features=["improved_unicode"] }

[dev-dependencies]
tempfile = "3.2"
