[package]
name = "simple_backup"
version = "1.2.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2018"
description = "A minimal application for doing backups."
readme = "README.md"
keywords = ["backup", "compression", "application"]

[dependencies]
tar = "0.4"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
yaml-rust = "0.4"
chrono = "0.4"
regex = "1.4"
path-clean = "0.1"
path-absolutize = "3.0"
indicatif = { version = "0.15", features = ["improved_unicode"] }
zstd = { version="0.7", features = ["zstdmt"] }

[dev-dependencies]
tempfile = "3.2"
