[package]
name = "simple_backup"
version = "1.3.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2021"
description = "A minimal application for doing backups."
readme = "README.md"
keywords = ["backup", "compression", "application"]

[dependencies]
tar = "0.4"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
yaml-rust = "0.4"
chrono = "0.4"
regex = "1.4"
path-clean = "0.1"
path-absolutize = "3.0"
indicatif = { version = "0.16", features = ["improved_unicode"] }
zstd = { version="0.9", features = ["zstdmt"] }
number_prefix = "0.4"
num_cpus = "1.13"
iced = { version = "0.3", features = ["smol"], optional = true }
rfd = { version ="0.6", optional = true }
dirs = { version = "4.0", optional = true }

[dev-dependencies]
tempfile = "3.2"

[features]
default = ["gui"]
gui = ["iced", "rfd", "dirs"]
