name: Build

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build binary on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          file: target/release/simple_backup
        - os: windows-latest
          file: target/release/simple_backup.exe
        - os: macOS-latest
          file: target/release/simple_backup


    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --release
    - name: Run
      run: ${{ matrix.file }} --help
    - name: Release
      uses: softprops/action-gh-release@v2.2.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ matrix.file }}
