name: Release Builds

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      os:
        required: true
        type: choice
        options: ['ubuntu', 'macos', 'windows']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build binary on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(format('["{0}"]', inputs.os || 'ubuntu", "macos", "windows')) }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build release
      run: cargo build --release

    - name: Set ENV Windows
      if: runner.os == 'Windows'
      run: echo "compiled_binary=target/release/simple_backup.exe" >> $GITHUB_ENV
    - name: Set ENV Linux
      if: runner.os == 'Linux'
      run: echo "compiled_binary=target/release/simple_backup" >> $GITHUB_ENV
    - name: Set ENV Mac
      if: runner.os == 'macOS'
      run: |
        mv target/release/simple_backup target/release/simple_backup_mac
        echo "compiled_binary=target/release/simple_backup_mac" >> $GITHUB_ENV

    - name: Run
      run: ${{ env.compiled_binary }} --help
    - name: Upload Release
      uses: softprops/action-gh-release@v2.1.0
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        files: ${{ env.compiled_binary }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      with:
        path: ${{ env.compiled_binary }}
        retention-days: 2
